export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART"
export const DELETE_ITEM_FROM_CART = "DELETE_ITEM_FROM_CART"
export const DELETE_CART = "DELETE_CART"
export const ADD_ORDER = "ADD_ORDER"

export const ADD_NEW_PRODUCT = "ADD_NEW_PRODUCT"
export const EDIT_PRODUCT = "EDIT_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"